### ISSUE TITLE
Upgrade from git-keeper-client from 0.2.2 to 0.3.0 produces error

### ISSUE THREAD

**Issue by sspickle** [git-keeper/git-keeper#194]
Do I need to upgrade client/server simultaneously? When I upgrade the client I get:

~ % gkeep query classes
Error loading info from JSON: ls: cannot access '/home/spicklemire/.gitkeeper/info': No such file or directory
cat: /home/spicklemire/.gitkeeper/info/: No such file or directory

But using 0.2.2 works fine. I have not upgraded the server. Any guidance on that?

thanks,
-Steve

**Comment by sommern** [comment]
@sspickle that's right, the 0.3.0 client will not work with the 0.2.2 server. The 0.3.0 update changed a fair amount about how things are organized on the server, and unfortunately there is no way to cleanly update from 0.2.2 to 0.3.0 on the server. For now your best bet would be to either stick with 0.2.2 client and server, or start fresh with a new server and install 0.3.0. The release notes for 0.3.0 are here, which might help you decide if the new features make it worth it to you to upgrade: https://github.com/git-keeper/git-keeper/releases/tag/0.3.0

**Comment by sspickle** [comment]
Ah, OK. That makes sense.

It is possible to "upgrade" a server by simply updating the python packages, or is there more surgery that needs to be done?

**Comment by sommern** [comment]
@sspickle There is no way to upgrade and keep any data about classes from the past, since certain data was moved from being stored in plain text files to a SQLite database, and certain files in faculty users' home directories was moved into `~/.gitkeeper`. If you simply updated the python packages, there would be a chance of files clashing in the future if you re-use class names from before the upgrade. You could give it a try with that caveat, but the safest thing would be to start over with a fresh server, or remove the user accounts and home directories on the server.

**Comment by sspickle** [comment]
Wow, big changes! OK, no worries. I'll use 0.2.2 for one more semester, and then upgrade over the summer. Thanks so much for the great software! :-)
